# Generated by Django 4.0 on 2023-11-10 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistrationmodel',
            name='state',
            field=models.CharField(default='NONE', max_length=100),
        ),
    ]
