# Generated by Django 4.0 on 2023-11-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='content',
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_file',
            field=models.FileField(default=None, upload_to='resumes/'),
        ),
    ]
