# Generated by Django 4.0 on 2023-11-14 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_resume_content_resume_resume_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
